language: node_js
node_js:
  - "4.2.4"
env:
  - YENV=production
install:
  - npm install
  - npm run build
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    cd desktop.bundles/index
    git clone --single-branch -b gh-pages https://github.com/aliosv/recruit-space.git

    rm -rf recruit-space/*.html
    cp index.html recruit-space
    rm -rf recruit-space/static/
    cp -r ../static/ recruit-space
    rm -rf recruit-space/*.css
    mv recruit-space/static/*.css recruit-space
    rm -rf recruit-space/*.js
    mv recruit-space/static/*.js recruit-space

    cd recruit-space
    git add static -f
    git add --all
    git -c user.name='travis' -c user.email='travis' commit -m $TRAVIS_COMMIT
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://aliosv:$GITHUB_API_KEY@github.com/aliosv/recruit-space gh-pages
    cd "$TRAVIS_BUILD_DIR"
  fi
